In [1]:
print(123)

123


print(123)

### 1 广播机制

#### 1.1 一维广播机制

In [5]:
[0,1,2,3]*3

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

In [8]:
import numpy as np
#sort 排序
arr1 = np.sort(np.array([0,1,2,3]*3)).reshape(4,3) #shape(4,3)
display(arr1)
arr2 = np.array([1,2,3]) #shape(3,)
display(arr2)
arr3 = arr1 + arr2 #arr2进行广播复制出四份
arr3 #jupyter会将变量输出

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([1, 2, 3])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

#### 1.2 二维广播机制

In [9]:
import numpy as np
arr1 = np.sort(np.array([0,1,2,3]*3)).reshape(4,3)
display(arr1)
arr2 = np.array([[1],[2],[3],[4]])
display(arr2)
arr3 = arr1 + arr2
arr3

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([[1],
       [2],
       [3],
       [4]])

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

#### 1.3 三维广播机制

In [10]:
import numpy as np
arr1 = np.array([0,1,2,3,4,5,6,7]*3).reshape(3,4,2) #shape(3,4,2)
display(arr1)
arr2 = np.array([0,1,2,3,4,5,6,7]).reshape(4,2) #shape(4,2)
display(arr2)
arr3 = arr1 + arr2
arr3

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]]])

### 2 通用函数

#### 2.1 元素级数字函数

In [15]:
import numpy as np
arr1 = np.array([1,4,8,9,16,25])
np.sqrt(arr1) #开方
np.square(arr1) #平方
np.clip(arr1,2,16) #取值2~16，输出array([ 2,  4,  8,  9, 16, 16])

array([ 2,  4,  8,  9, 16, 16])

In [13]:
x = np.array([1,5,2,9,3,6,8])
y = np.array([2,4,3,7,1,9,0])
np.maximum(x,y) #返回两个数组中的比较大的值
arr2 = np.random.randint(0,10,size = (5,5))
np.inner(arr2[0],arr2) #返回一堆数组向量内积

array([ 79,  73, 103,  48,  54], dtype=int32)

#### 2.2 where函数

In [1]:
import numpy as np
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
cond = np.array([True,False,True,True,False])
np.where(cond,arr1,arr2) #True选择arr1，False选择arr2的值
#输出arr([1,4,5,7,10])

array([ 1,  4,  5,  7, 10])

In [4]:
arr3 = np.random.randint(0,30,size = 20)
display(arr3)
np.where(arr3 < 15,arr3,-15)

array([29, 22, 27, 11,  0,  4, 20, 10, 24,  1, 22, 12, 21, 18, 14, 20,  2,
       20, 14, 29], dtype=int32)

array([-15, -15, -15,  11,   0,   4, -15,  10, -15,   1, -15,  12, -15,
       -15,  14, -15,   2, -15,  14, -15], dtype=int32)

#### 2.3 排序方法

In [9]:
import numpy as np
arr = np.array([9,3,11,6,17,5,4,15,1])
display(arr)
arr.sort() #直接改变原数组
arr

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

In [11]:
np.sort(arr) #返回深拷贝排序结果
arr = np.array([9,3,11,6,17,5,4,15,1])
index = arr.argsort() #返回从小到大排序索引 array([8, 1, 6, 5, 3, 0, 2, 7, 4])
display(arr,index)
#根据索引来排序
arr[index]

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

array([8, 1, 6, 5, 3, 0, 2, 7, 4])

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

#### 2.4 集合运算

In [2]:
import numpy as np

A = np.array([2, 4, 6, 8])
B = np.array([3, 4, 5, 6])

print(np.intersect1d(A, B))  # 交集 -> [4 6]
print(np.union1d(A, B))      # 并集 -> [2 3 4 5 6 8]
print(np.setdiff1d(A, B))    # 差集 (A - B) -> [2 8]


[4 6]
[2 3 4 5 6 8]
[2 8]


#### 2.5 数学和统计函数

In [7]:
import numpy as np
arr1 = np.array([1,7,2,19,23,0,88,11,6,11])
print(arr1.min()) #计算最小值
print(arr1.argmax()) #计算最大值的索引
print(np.argwhere(arr1 > 20)) #返回大于20的元素的索引
print(np.cumsum(arr1)) #计算累加和

0
6
[[4]
 [6]]
[  1   8  10  29  52  52 140 151 157 168]


In [10]:
arr2 = np.random.randint(0,10,size = (4,5))
display(arr2)
print(arr2.mean(axis = 0)) #计算列的平均值
print(arr2.mean(axis = 1)) #计算行的平均值
print(np.cov(arr2,rowvar = True)) #协方差公式
print(np.corrcoef(arr2,rowvar = True)) #相关性系数

array([[3, 2, 6, 5, 9],
       [5, 6, 5, 7, 6],
       [4, 3, 0, 4, 2],
       [6, 5, 9, 3, 6]], dtype=int32)

[4.5  4.   5.   4.75 5.75]
[5.  5.8 2.6 5.8]
[[ 7.5   0.25 -2.25  1.5 ]
 [ 0.25  0.7   0.65 -1.55]
 [-2.25  0.65  2.8  -3.1 ]
 [ 1.5  -1.55 -3.1   4.7 ]]
[[ 1.          0.10910895 -0.49099025  0.25264558]
 [ 0.10910895  1.          0.46428571 -0.85454266]
 [-0.49099025  0.46428571  1.         -0.85454266]
 [ 0.25264558 -0.85454266 -0.85454266  1.        ]]


### 3 线性代数

#### 3.1 矩阵乘积（内积）

In [12]:
A = np.array([[4,2,3],
              [1,3,1]]) #shape(2,3)
B = np.array([[2,7],
              [-5,-7],
              [9,3]])
np.dot(A,B) #矩阵运算A的最后一维和B的第一维必须一致

array([[ 25,  23],
       [ -4, -11]])

In [13]:
A @ B #符号 @ 表示矩阵乘积运算

array([[ 25,  23],
       [ -4, -11]])

#### 3.2 矩阵其他计算

In [15]:
from numpy.linalg import inv,det,eig,qr,svd
A = np.array([[1,2,3],
              [2,3,4],
              [4,5,8]]) #shape(3,3)
inv(A) #逆矩阵

array([[-2.00000000e+00,  5.00000000e-01,  5.00000000e-01],
       [ 5.92118946e-16,  2.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00, -1.50000000e+00,  5.00000000e-01]])

In [16]:
det(A)

np.float64(-2.0000000000000004)

In [17]:
eig(A)

EigResult(eigenvalues=array([12.06912579+0.j, -0.44310504+0.j,  0.37397924+0.j]), eigenvectors=array([[ 0.30810498+0.j,  0.91959374+0.j, -0.02891232+0.j],
       [ 0.43997714+0.j, -0.08984659+0.j, -0.8289074 +0.j],
       [ 0.84349952+0.j, -0.38245906+0.j,  0.55863817+0.j]]))

In [18]:
qr(A)

QRResult(Q=array([[-0.21821789, -0.81649658, -0.53452248],
       [-0.43643578, -0.40824829,  0.80178373],
       [-0.87287156,  0.40824829, -0.26726124]]), R=array([[-4.58257569, -6.11010093, -9.38336928],
       [ 0.        , -0.81649658, -0.81649658],
       [ 0.        ,  0.        , -0.53452248]]))

In [19]:
svd(A)

SVDResult(U=array([[-0.30590267,  0.80403283,  0.5098576 ],
       [-0.44236633,  0.35417612, -0.82393647],
       [-0.84305136, -0.4775882 ,  0.24733363]]), S=array([12.15104911,  0.48819731,  0.3371482 ]), Vh=array([[-0.37551002, -0.50647159, -0.77619505],
       [-0.81517804,  0.57897293,  0.01658628],
       [-0.44099544, -0.63896548,  0.63027465]]))