### 1 数据类型

In [6]:
import numpy as np

arr1 = np.array([1,2,3,127,126],dtype = np.int8)
display(arr1,2**8) #256 数字范围：-123~0~127

arr2 = np.array([1,2,5,8,255,253],dtype = np.uint8) #无符号的8位表示数字（无负号）
display(arr2) #0~255

array([  1,   2,   3, 127, 126], dtype=int8)

256

array([  1,   2,   5,   8, 255, 253], dtype=uint8)

In [7]:
arr1 = np.random.randint(0,150,size = (10000,3),dtype = np.int16)
arr2 = arr1.astype(np.int64) #原数据的基础上，对数据类型进行调整
display(arr1,arr2)
np.save('arr1',arr1)
np.save('arr2',arr2)

array([[ 13,  94,  94],
       [130,  72,  93],
       [ 79,  37,   7],
       ...,
       [ 27, 113, 113],
       [144,  97, 146],
       [ 11,  46, 118]], shape=(10000, 3), dtype=int16)

array([[ 13,  94,  94],
       [130,  72,  93],
       [ 79,  37,   7],
       ...,
       [ 27, 113, 113],
       [144,  97, 146],
       [ 11,  46, 118]], shape=(10000, 3))

In [8]:
arr3 = np.random.randn(100)
display(arr3,arr3.dtype)
arr4 = arr3.astype(np.float16)
display(arr4)

array([ 0.97976611, -0.54764422,  1.51724197,  0.60194243, -0.01568119,
        0.35188868, -0.27121853,  0.09098556,  0.17311041, -1.09800366,
       -0.8265875 ,  0.09910121,  1.33704573,  0.03728936,  0.47939297,
       -0.1137377 ,  0.91386266, -0.61523359,  0.42290427, -1.58671196,
       -1.60839026,  0.47400161, -0.68382484,  1.16857831, -0.33431933,
        1.75913943,  0.5895675 , -1.10342129,  0.66744979, -1.08122098,
       -0.11537411, -0.8188946 , -0.20641753,  1.70861079,  0.66559167,
       -1.39024047,  3.03207127,  0.64218498,  0.31049819,  0.09085791,
        0.22662401, -0.19291708,  1.35008586,  1.48578011,  1.83845384,
        0.41245642, -1.2643047 , -0.18884438,  0.14646552,  0.24113948,
        0.12107805, -1.29688521, -1.53628573,  1.78880023,  1.26015987,
        1.0429066 , -0.44759829,  0.51200298,  1.10274493,  0.33951826,
       -0.8682868 , -0.158523  , -1.08291046,  0.00983968,  0.780901  ,
        1.32210204, -0.92332851, -0.57997824, -0.4591477 ,  0.32

dtype('float64')

array([ 0.98   , -0.548  ,  1.518  ,  0.602  , -0.01569,  0.3518 ,
       -0.2712 ,  0.091  ,  0.1731 , -1.098  , -0.8267 ,  0.0991 ,
        1.337  ,  0.0373 ,  0.4795 , -0.1137 ,  0.914  , -0.615  ,
        0.4229 , -1.587  , -1.608  ,  0.474  , -0.6836 ,  1.169  ,
       -0.3342 ,  1.759  ,  0.5894 , -1.104  ,  0.6675 , -1.081  ,
       -0.11536, -0.819  , -0.2064 ,  1.709  ,  0.6655 , -1.391  ,
        3.031  ,  0.642  ,  0.3105 ,  0.0909 ,  0.2267 , -0.1929 ,
        1.35   ,  1.485  ,  1.839  ,  0.4124 , -1.265  , -0.1888 ,
        0.1465 ,  0.2411 ,  0.1211 , -1.297  , -1.536  ,  1.789  ,
        1.26   ,  1.043  , -0.4475 ,  0.512  ,  1.103  ,  0.3396 ,
       -0.868  , -0.1586 , -1.083  ,  0.00984,  0.781  ,  1.322  ,
       -0.9233 , -0.58   , -0.4592 ,  0.3274 , -0.853  ,  1.351  ,
        0.4688 , -0.1146 ,  0.22   , -0.4902 , -1.348  ,  2.113  ,
        0.6655 , -1.179  , -0.07935, -0.1251 ,  0.5156 ,  0.068  ,
       -0.622  ,  1.64   , -1.068  ,  0.676  ,  0.991  ,  0.15

### 2 数组运算

#### 2.1 普通运算

In [11]:
arr1 = np.random.randint(0,10,size = (3,5))
display(arr1,arr1*2,arr1/5)

array([[8, 3, 3, 3, 1],
       [4, 4, 7, 0, 1],
       [4, 4, 2, 2, 3]], dtype=int32)

array([[16,  6,  6,  6,  2],
       [ 8,  8, 14,  0,  2],
       [ 8,  8,  4,  4,  6]], dtype=int32)

array([[1.6, 0.6, 0.6, 0.6, 0.2],
       [0.8, 0.8, 1.4, 0. , 0.2],
       [0.8, 0.8, 0.4, 0.4, 0.6]])

In [12]:
#幂运算
display(arr1**2)

array([[64,  9,  9,  9,  1],
       [16, 16, 49,  0,  1],
       [16, 16,  4,  4,  9]], dtype=int32)

In [13]:
display(arr1,arr1//2,arr1%2)

array([[8, 3, 3, 3, 1],
       [4, 4, 7, 0, 1],
       [4, 4, 2, 2, 3]], dtype=int32)

array([[4, 1, 1, 1, 0],
       [2, 2, 3, 0, 0],
       [2, 2, 1, 1, 1]], dtype=int32)

array([[0, 1, 1, 1, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1]], dtype=int32)

#### 2.2 逻辑运算

In [18]:
display(arr1,arr1 == 3,arr1 < 5)

array([[8, 3, 3, 3, 1],
       [4, 4, 7, 0, 1],
       [4, 4, 2, 2, 3]], dtype=int32)

array([[False,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

array([[False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [19]:
display((arr1 > 2) & (arr1 <= 4))

array([[False,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False,  True]])

In [21]:
display(~(arr1 > 2))

array([[False, False, False, False,  True],
       [False, False, False,  True,  True],
       [False, False,  True,  True, False]])

In [24]:
display(arr1,(arr1 == 1)|(arr1 == 8))

array([[8, 3, 3, 3, 1],
       [4, 4, 7, 0, 1],
       [4, 4, 2, 2, 3]], dtype=int32)

array([[ True, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

#### 2.3 *=、+=、/=、-=

In [25]:
arr1

array([[8, 3, 3, 3, 1],
       [4, 4, 7, 0, 1],
       [4, 4, 2, 2, 3]], dtype=int32)

In [29]:
arr1 -= 10
arr1

array([[-32, -37, -37, -37, -39],
       [-36, -36, -33, -40, -39],
       [-36, -36, -38, -38, -37]], dtype=int32)

In [31]:
arr1 +=20
arr1

array([[8, 3, 3, 3, 1],
       [4, 4, 7, 0, 1],
       [4, 4, 2, 2, 3]], dtype=int32)

In [32]:
arr1 *= 2
arr1

array([[16,  6,  6,  6,  2],
       [ 8,  8, 14,  0,  2],
       [ 8,  8,  4,  4,  6]], dtype=int32)

In [35]:
#原数据数据类型是int，要先转变数据类型，再进行除等于运算
arr2 = arr1.astype(np.float32)
display(arr1,arr2)
arr2 /= 2
arr2

array([[16,  6,  6,  6,  2],
       [ 8,  8, 14,  0,  2],
       [ 8,  8,  4,  4,  6]], dtype=int32)

array([[16.,  6.,  6.,  6.,  2.],
       [ 8.,  8., 14.,  0.,  2.],
       [ 8.,  8.,  4.,  4.,  6.]], dtype=float32)

array([[8., 3., 3., 3., 1.],
       [4., 4., 7., 0., 1.],
       [4., 4., 2., 2., 3.]], dtype=float32)

#### 2.4 数组和数组运算

In [37]:
arr1
arr3 = np.array([1,2,3,4,5])
display(arr1,arr3)

array([[16,  6,  6,  6,  2],
       [ 8,  8, 14,  0,  2],
       [ 8,  8,  4,  4,  6]], dtype=int32)

array([1, 2, 3, 4, 5])

In [38]:
arr1 + arr3

array([[17,  8,  9, 10,  7],
       [ 9, 10, 17,  4,  7],
       [ 9, 10,  7,  8, 11]])

### 3 复制和视图

#### 3.1 完全没有复制

In [41]:
import numpy as np
a = np.random.randint(0,100,size = (4,5))
b = a
print(a is b) #返回True，a和b是两个不同名字对应同一个内存对象
b[0,0] = 1024 #命运共同体
display(a,b)

True


array([[1024,   97,   13,   38,   69],
       [  95,   47,   87,   64,   10],
       [  40,   67,   86,   72,   23],
       [  21,   53,   70,   45,    8]], dtype=int32)

array([[1024,   97,   13,   38,   69],
       [  95,   47,   87,   64,   10],
       [  40,   67,   86,   72,   23],
       [  21,   53,   70,   45,    8]], dtype=int32)

#### 3.2 查看或浅拷贝

In [42]:
import numpy as np
a = np.random.randint(0,100,size = (4,5))
b = a.view()
print(a is b)
print(b.base is a)
print(b.flags.owndata)
print(a.flags.owndata)
b[0,0] = 1024
display(a,b)

False
True
False
True


array([[1024,   29,   81,   14,   89],
       [  83,   48,   15,   99,   24],
       [  12,   28,   57,    1,   79],
       [  90,   48,   25,   91,   70]], dtype=int32)

array([[1024,   29,   81,   14,   89],
       [  83,   48,   15,   99,   24],
       [  12,   28,   57,    1,   79],
       [  90,   48,   25,   91,   70]], dtype=int32)

#### 3.3 深拷贝

In [43]:
import numpy as np
a = np.random.randint(0,100,size = (4,5))
b = a.copy()
print(b is a)
print(b.base is a)
print(b.flags.owndata)
print(a.flags.owndata)
b[0,0] = 1024
display(a,b)

False
False
True
True


array([[18, 96, 38, 99, 51],
       [29,  3, 83, 61, 30],
       [91, 43, 60, 68, 55],
       [ 5,  5, 31, 59, 28]], dtype=int32)

array([[1024,   96,   38,   99,   51],
       [  29,    3,   83,   61,   30],
       [  91,   43,   60,   68,   55],
       [   5,    5,   31,   59,   28]], dtype=int32)

### 4 基本的索引和切片

#### 4.1 深拷贝的应用

In [44]:
import numpy as np
import gc #垃圾回收
a = np.arange(1e8)
display(a)
b = a[::1000000].copy()
del a #不再需要a，删除大内存的a
gc.collect()
display(b,b.shape) #shape(100,)

array([0.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 9.9999997e+07,
       9.9999998e+07, 9.9999999e+07], shape=(100000000,))

array([       0.,  1000000.,  2000000.,  3000000.,  4000000.,  5000000.,
        6000000.,  7000000.,  8000000.,  9000000., 10000000., 11000000.,
       12000000., 13000000., 14000000., 15000000., 16000000., 17000000.,
       18000000., 19000000., 20000000., 21000000., 22000000., 23000000.,
       24000000., 25000000., 26000000., 27000000., 28000000., 29000000.,
       30000000., 31000000., 32000000., 33000000., 34000000., 35000000.,
       36000000., 37000000., 38000000., 39000000., 40000000., 41000000.,
       42000000., 43000000., 44000000., 45000000., 46000000., 47000000.,
       48000000., 49000000., 50000000., 51000000., 52000000., 53000000.,
       54000000., 55000000., 56000000., 57000000., 58000000., 59000000.,
       60000000., 61000000., 62000000., 63000000., 64000000., 65000000.,
       66000000., 67000000., 68000000., 69000000., 70000000., 71000000.,
       72000000., 73000000., 74000000., 75000000., 76000000., 77000000.,
       78000000., 79000000., 80000000., 81000000., 

(100,)

#### 4.2 基本的索引和切片

索引

In [45]:
arr2 = np.random.randint(0,100,size = (5,4))
display(arr2)

array([[81,  8, 38, 51],
       [97, 23, 60, 40],
       [45,  1, 15,  0],
       [89, 15, 99, 78],
       [ 7, 47, 58, 27]], dtype=int32)

In [46]:
arr2[0,0]

np.int32(81)

In [47]:
arr2[4,3]

np.int32(27)

In [48]:
arr2[-1,-1]

np.int32(27)

In [50]:
arr2[[0,0],[0,1]]

array([81,  8], dtype=int32)

切片

In [51]:
display(arr2,arr2[1:3])

array([[81,  8, 38, 51],
       [97, 23, 60, 40],
       [45,  1, 15,  0],
       [89, 15, 99, 78],
       [ 7, 47, 58, 27]], dtype=int32)

array([[97, 23, 60, 40],
       [45,  1, 15,  0]], dtype=int32)

In [52]:
arr2[2:4,1:3]

array([[ 1, 15],
       [15, 99]], dtype=int32)

In [53]:
arr2[2:4,[0,3]]

array([[45,  0],
       [89, 78]], dtype=int32)

In [54]:
arr2[::2]

array([[81,  8, 38, 51],
       [45,  1, 15,  0],
       [ 7, 47, 58, 27]], dtype=int32)

In [55]:
arr2[1::2]

array([[97, 23, 60, 40],
       [89, 15, 99, 78]], dtype=int32)

In [56]:
arr2[::2,1::2]

array([[ 8, 51],
       [ 1,  0],
       [47, 27]], dtype=int32)

#### 4.3 花式索引和索引技巧

In [4]:
import numpy as np

In [5]:
arr2 = np.random.randint(0,100,size = (5,4))

In [6]:
display(arr2,arr2[[0,1,0,2,0]])

array([[21, 13, 39, 58],
       [85, 86, 31, 31],
       [93,  2,  3, 25],
       [62, 41,  8, 79],
       [83,  2, 70,  9]], dtype=int32)

array([[21, 13, 39, 58],
       [85, 86, 31, 31],
       [21, 13, 39, 58],
       [93,  2,  3, 25],
       [21, 13, 39, 58]], dtype=int32)

In [8]:
arr2[[0,3,3,3]][:,[1,3,3]]

array([[13, 58, 58],
       [41, 79, 79],
       [41, 79, 79],
       [41, 79, 79]], dtype=int32)

In [9]:
arr2[np.ix_([0,3,3,3],[1,3,3])]

array([[13, 58, 58],
       [41, 79, 79],
       [41, 79, 79],
       [41, 79, 79]], dtype=int32)

boolean类型的索引

In [11]:
arr1 = np.random.randint(0,100,size=(50))
cond = arr1 > 80
arr1[cond]

array([97, 92, 99, 85, 95], dtype=int32)

In [13]:
cond2 = (arr1 < 10) | (arr1 > 90)
arr1[cond2]

array([97,  4, 92,  9, 99, 95,  7], dtype=int32)

In [15]:
display(arr1,arr1[::-1],arr1[::-3])

array([69, 46, 65, 29, 16, 36, 53, 97, 38, 37, 20, 24, 70, 19,  4, 92, 22,
       72,  9, 21, 14, 79, 10, 24, 40, 99, 53, 51, 79, 66, 14, 45, 12, 26,
       37, 85, 76, 29, 53, 13, 67, 79, 27, 95, 13, 50, 17, 35, 13,  7],
      dtype=int32)

array([ 7, 13, 35, 17, 50, 13, 95, 27, 79, 67, 13, 53, 29, 76, 85, 37, 26,
       12, 45, 14, 66, 79, 51, 53, 99, 40, 24, 10, 79, 14, 21,  9, 72, 22,
       92,  4, 19, 70, 24, 20, 37, 38, 97, 53, 36, 16, 29, 65, 46, 69],
      dtype=int32)

array([ 7, 17, 95, 67, 29, 37, 45, 79, 99, 10, 21, 22, 19, 20, 97, 16, 46],
      dtype=int32)

### 5 形状操作

#### 5.1 reshape

In [16]:
arr = np.random.randint(0,100,size = (3,6))
arr

array([[98, 78, 18,  6, 38, 17],
       [46, 26,  2, 31, 27, 39],
       [95, 40, 17,  0, 99, 13]], dtype=int32)

In [17]:
arr.reshape(9,2)

array([[98, 78],
       [18,  6],
       [38, 17],
       [46, 26],
       [ 2, 31],
       [27, 39],
       [95, 40],
       [17,  0],
       [99, 13]], dtype=int32)

#### 5.2 转置

In [19]:
# 行变列，列变行
arr

array([[98, 78, 18,  6, 38, 17],
       [46, 26,  2, 31, 27, 39],
       [95, 40, 17,  0, 99, 13]], dtype=int32)

In [20]:
arr.T

array([[98, 46, 95],
       [78, 26, 40],
       [18,  2, 17],
       [ 6, 31,  0],
       [38, 27, 99],
       [17, 39, 13]], dtype=int32)

In [22]:
arr.reshape(6,3)

array([[98, 78, 18],
       [ 6, 38, 17],
       [46, 26,  2],
       [31, 27, 39],
       [95, 40, 17],
       [ 0, 99, 13]], dtype=int32)

#### 5.3 堆叠

In [36]:
arr4 = arr1[::7]
arr4

array([69, 97,  4, 79, 79, 85, 27,  7], dtype=int32)

In [37]:
arr5 = arr1[::8]
arr5

array([69, 38, 22, 40, 12, 67, 13], dtype=int32)

In [38]:
np.concatenate([arr4,arr4,arr4,arr5])

array([69, 97,  4, 79, 79, 85, 27,  7, 69, 97,  4, 79, 79, 85, 27,  7, 69,
       97,  4, 79, 79, 85, 27,  7, 69, 38, 22, 40, 12, 67, 13],
      dtype=int32)

In [39]:
arr1 = np.random.randint(0,10,size = (5,3))
arr2 = np.random.randint(0,10,size = (2,3))
arr3 = np.random.randint(0,10,size = (5,2))
display(arr1,arr2,arr3)

array([[5, 0, 3],
       [9, 4, 1],
       [0, 4, 3],
       [2, 6, 0],
       [3, 2, 7]], dtype=int32)

array([[9, 1, 7],
       [5, 4, 8]], dtype=int32)

array([[3, 5],
       [9, 3],
       [5, 7],
       [2, 5],
       [4, 3]], dtype=int32)

In [40]:
np.concatenate([arr1,arr2])

array([[5, 0, 3],
       [9, 4, 1],
       [0, 4, 3],
       [2, 6, 0],
       [3, 2, 7],
       [9, 1, 7],
       [5, 4, 8]], dtype=int32)

In [42]:
np.concatenate([arr1,arr3],axis = 1)

array([[5, 0, 3, 3, 5],
       [9, 4, 1, 9, 3],
       [0, 4, 3, 5, 7],
       [2, 6, 0, 2, 5],
       [3, 2, 7, 4, 3]], dtype=int32)