### 基本操作

#### 1.1 创建

In [6]:
import numpy as np

In [7]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [8]:
arr2 = np.random.randint(0,100,size = (10))
arr2

array([76, 51, 54, 96, 38, 77,  6, 58, 26, 13], dtype=int32)

In [9]:
arr3 = np.random.randn(10)
arr3

array([-0.71889741,  2.10291048,  2.52410133,  0.97411427, -1.55466254,
       -1.36163482,  0.25736616, -0.56864344, -1.19395274,  1.78942189])

In [12]:
np.random.randint(-50,50,size=(5,3))

array([[  2, -47, -15],
       [ 16, -32, -22],
       [-35, -12, -19],
       [  5, -19, -24],
       [ 27,  40, -19]], dtype=int32)

In [13]:
np.ones(shape =(5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.zeros_like(arr3)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# 等差数列
arr1 = np.arange(0,10,3)
arr1

array([0, 3, 6, 9])

In [20]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [21]:
# 等比数列
np.logspace(1,10,num = 10,base = 2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

#### 1.2查看操作

In [22]:
arr = np.random.randint(0,100,size = (3,4,5))
arr

array([[[24, 87, 65, 16, 58],
        [88, 49, 19, 94, 23],
        [87, 81, 55, 83, 36],
        [19, 36, 79, 49, 58]],

       [[ 8, 49, 66, 63, 46],
        [63, 77, 40, 42, 49],
        [32,  2, 26, 35, 74],
        [25,  2, 37, 99, 11]],

       [[28, 54, 79, 40, 84],
        [21,  7, 68,  9, 45],
        [84, 79, 27, 51, 16],
        [77, 97,  5, 27, 60]]], dtype=int32)

In [23]:
arr.shape

(3, 4, 5)

In [24]:
arr.dtype

dtype('int32')

In [25]:
arr.size

60

In [26]:
arr.ndim

3

#### 1.3 IO操作

In [31]:
arr1 = np.random.random(size = (3,5))
arr1

array([[0.83307598, 0.66547911, 0.57565801, 0.21193722, 0.32190722],
       [0.93010028, 0.55773354, 0.51157649, 0.84511802, 0.07367661],
       [0.36680147, 0.14197547, 0.76815315, 0.51121476, 0.16688443]])

In [33]:
# 文件后缀，默认是npz
np.save('./arr1',arr1)

In [34]:
np.load('./arr1.npy')

array([[0.83307598, 0.66547911, 0.57565801, 0.21193722, 0.32190722],
       [0.93010028, 0.55773354, 0.51157649, 0.84511802, 0.07367661],
       [0.36680147, 0.14197547, 0.76815315, 0.51121476, 0.16688443]])

In [35]:
arr2 = np.logspace(1,10,num = 10,base = 2)
arr2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [36]:
 np.savez('./file2',arr_x = arr1,arr_y = arr2)

In [37]:
np.load('./file2.npz')['arr_x']

array([[0.83307598, 0.66547911, 0.57565801, 0.21193722, 0.32190722],
       [0.93010028, 0.55773354, 0.51157649, 0.84511802, 0.07367661],
       [0.36680147, 0.14197547, 0.76815315, 0.51121476, 0.16688443]])

In [38]:
np.load('./file2.npz')['arr_y']

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [40]:
np.savetxt('./arr1.txt',arr1,delimiter = ',')

In [41]:
np.savetxt('./arr1.txt',arr1,delimiter = ',',fmt = '%.5f')

In [42]:
np.savetxt('./arr1.csv',arr1,delimiter = ';',fmt = '%.5f')